.Dd November 23, 2023
.Dt URL-ESCAPE 1
.Os
.Sh NAME
.Nm url-escape
.Nd URL-escape and URL-unescape data
.Sh SYNOPSIS
.Nm url-escape
.Op Fl d
.Op Fl n
.Sh DESCRIPTION
Reads from standard input,
URL-escapes
.Pq or unescapes, with Fl d ,
and writes to standard output.
A trailing newline is added unless
.Fl n
is given.
.Pp
Escaping and unescaping is performed with
.Xr curl_easy_escape 3
and
.Xr curl_easy_unescape 3
respectively.
.Sh EXIT STATUS
Exits 0 on success,
.Dv EX_USAGE
.Pq 64
on usage error,
or 1 on any other error.
.Sh EXAMPLES
Escape a string:
.Bd -literal -offset indent
$ echo -n 'Hello, World!' | url-escape
Hello%2C%20World%21
.Ed
.Pp
Escape a string and unescape it again:
.Bd -literal -offset indent
$ echo -n 'Hello, World!' | url-escape -n | url-escape -d
Hello, World!
.Ed
.Sh SEE ALSO
.Xr curl_easy_escape 3 ,
.Xr curl_easy_unescape 3
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
