on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libcurl4-openssl-dev
    - run: make check

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: make check

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: podman build .
